server:
  port: 8761

eureka:
  instance:
    hostname: localhost

  server:
    enable-self-preservation: true
    renewal-percent-threshold: 0.30

  client:
    register-with-eureka: false
    fetch-registry: false